#pragma once

#include <chrono>

#define BOUSKNET_SETTINGS_ENABLED 1
#define BOUSKNET_SETTINGS_DISABLED 0

// Enable serialization of float32
//#define BOUSKNET_ALLOW_FLOAT32_SERIALIZATION BOUSKNET_SETTINGS_ENABLED

// Default UDP timeout
#define BOUSKNET_DEFAULT_UDP_TIMEOUT std::chrono::seconds(1)

// Allow use of network simulator
#define BOUSKNET_ALLOW_NETWORK_SIMULATOR BOUSKNET_SETTINGS_ENABLED


// Default value for unset settings
#ifndef BOUSKNET_ALLOW_FLOAT32_SERIALIZATION
	#define BOUSKNET_ALLOW_FLOAT32_SERIALIZATION BOUSKNET_SETTINGS_DISABLED
#endif // BOUSKNET_ALLOW_FLOAT32_SERIALIZATION

#ifndef BOUSKNET_DEFAULT_UDP_TIMEOUT
	#define BOUSKNET_DEFAULT_UDP_TIMEOUT std::chrono::seconds(1)
#endif // BOUSKNET_DEFAULT_UDP_TIMEOUT

#ifndef BOUSKNET_ALLOW_NETWORK_SIMULATOR
	#define BOUSKNET_ALLOW_NETWORK_SIMULATOR BOUSKNET_SETTINGS_DISABLED
#endif // BOUSKNET_ALLOW_NETWORK_SIMULATOR